### ISSUE TITLE
PMU for rzg2l soc

### ISSUE THREAD

**Issue by lynchwy** [renesas-rz/rz_linux-cip#2]
How to enable PMU related configuration on the SoC of the RZG2L series?

**Comment by seebe** [comment]
The RZ/G2L does not support power saving modes such as Suspend to RAM. Standard features like haling a CPU or reducing clock speeds are supported through the /sys interface.

**Comment by lynchwy** [comment]
sorry, my question is not clearly described, how to turn on PMU (Performance Monitoring Unit), Using this command (perf list cache), there is no output.

**Comment by seebe** [comment]
Oh, that's what you mean.
Honestly, I have not tried perf yet on this device so I'm not sure.

It looks like you have to enable it in the kernel.
https://github.com/renesas-rz/rz_linux-cip/blob/rz-5.10-cip41/arch/arm64/kernel/Makefile#L35
obj-$(CONFIG_PERF_EVENTS)		+= perf_regs.o perf_callchain.o
obj-$(CONFIG_HW_PERF_EVENTS)		+= perf_event.o


But, I do see that CA55 support made it into the 5.10 kernel.
https://github.com/renesas-rz/rz_linux-cip/blob/rz-5.10-cip41/arch/arm64/kernel/perf_event.c#L1220

**Comment by lynchwy** [comment]
Thanks for the reply.The following patch is missing from my code.
After merging, the perf functions normally.
https://github.com/renesas-rz/rz_linux-cip/commit/18fd80589c3617d0b3da6b79ac517773fcecc6fd
